<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class Blog
{
    public int BlogId { get; set; }

<<<<<<< Updated upstream
    public string Title { get; set; }

    public string Content { get; set; }

    public int Author { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Image { get; set; }

    public virtual User AuthorNavigation { get; set; }
}
=======
    public string Title { get; set; } = null!;

    public string Content { get; set; } = null!;

    public int AuthorId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string? Image { get; set; }

    public virtual User Author { get; set; } = null!;
}
>>>>>>> Stashed changes
