// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ConsultationBooking
{
    public Guid ConsultationBookingId { get; set; }

    public Guid UserId { get; set; }

    public Guid ConsultantId { get; set; }

    public DateTime Datetime { get; set; }

    public string Title { get; set; }

    public string LinkConsultation { get; set; }

    public string Status { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual User User { get; set; }
}