<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class ConsultantUserSchedule
{
    public int ScheduleId { get; set; }

    public int UserId { get; set; }

    public int ConsultantId { get; set; }

    public int? ConsultationBookingId { get; set; }

    public DateTime ScheduleDateTime { get; set; }

    public int? DurationMinutes { get; set; }

<<<<<<< Updated upstream
    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual ConsultationBooking ConsultationBooking { get; set; }

    public virtual User User { get; set; }
}
=======
    public string? Status { get; set; }

    public string? Notes { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual Consultant Consultant { get; set; } = null!;

    public virtual ConsultationBooking? ConsultationBooking { get; set; }

    public virtual User User { get; set; } = null!;
}
>>>>>>> Stashed changes
