<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class Consultant
{
    public int ConsultantId { get; set; }

    public int UserId { get; set; }

<<<<<<< Updated upstream
    public string Degree { get; set; }

    public int? ExperienceYears { get; set; }

    public string Bio { get; set; }
=======
    public string? Degree { get; set; }

    public int? ExperienceYears { get; set; }

    public string? Bio { get; set; }
>>>>>>> Stashed changes

    public virtual ICollection<ConsultantUserSchedule> ConsultantUserSchedules { get; set; } = new List<ConsultantUserSchedule>();

    public virtual ICollection<ConsultationBooking> ConsultationBookings { get; set; } = new List<ConsultationBooking>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

<<<<<<< Updated upstream
    public virtual User User { get; set; }
}
=======
    public virtual User User { get; set; } = null!;
}
>>>>>>> Stashed changes
