// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Feedback
{
    public Guid FeedbackId { get; set; }

    public Guid UserId { get; set; }

    public Guid? TestBookingId { get; set; }

    public Guid? ConsultationBookingId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual User User { get; set; }
}