// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Models;

[Table("Group")]
public partial class Group
{
    [Key]
    [StringLength(255)]
    public string Name { get; set; }

    [InverseProperty("GroupNameNavigation")]
    public virtual ICollection<Connection> Connections { get; set; } = new List<Connection>();
}