<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class MenstrualCycle
{
    public int CyclesId { get; set; }

    public int UserId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? AverageLength { get; set; }

<<<<<<< Updated upstream
    public virtual User User { get; set; }
}
=======
    public virtual User User { get; set; } = null!;
}
>>>>>>> Stashed changes
