// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class OvulationReminder
{
    public Guid ReminderId { get; set; }

    public Guid UserId { get; set; }

    public Guid CyclesId { get; set; }

    public DateOnly ReminderDate { get; set; }

    public string Type { get; set; }

    public string Note { get; set; }

    public int? CycleDay { get; set; }

    public virtual MenstrualCycle Cycles { get; set; }

    public virtual User User { get; set; }
}