<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int UserId { get; set; }

    public int? TestBooking { get; set; }

    public decimal Amount { get; set; }

<<<<<<< Updated upstream
    public string Method { get; set; }

    public string Status { get; set; }

    public DateTime? TransactionTime { get; set; }

    public virtual TestBooking TestBookingNavigation { get; set; }

    public virtual User User { get; set; }
}
=======
    public string Method { get; set; } = null!;

    public string? Status { get; set; }

    public DateTime? TransactionTime { get; set; }

    public virtual TestBooking? TestBookingNavigation { get; set; }

    public virtual User User { get; set; } = null!;
}
>>>>>>> Stashed changes
