// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Question
{
    public int QuestionId { get; set; }

    public int ConsultantId { get; set; }

    public int UserId { get; set; }

    public string QuestionText { get; set; }

    public string AnswerText { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual User User { get; set; }
}