// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

[Table("Role")]
[Index("RoleName", Name = "UQ__Role__B194786130E93023", IsUnique = true)]
public partial class Role
{
    [Key]
    [Column("roleId")]
    public Guid RoleId { get; set; }

    [Column("roleName")]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleName { get; set; } = null!;

    [InverseProperty("Role")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}