<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class Role
{
    public int RoleId { get; set; }

<<<<<<< Updated upstream
    public string RoleName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
=======
    public string RoleName { get; set; } = null!;

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
>>>>>>> Stashed changes
