// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Repository.Models;

public partial class SWP391GHSMContext : DbContext
{
    public SWP391GHSMContext()
    {
        
    }
    public SWP391GHSMContext(DbContextOptions<SWP391GHSMContext> options)
        : base(options)
    {
    }
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));
    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<Consultant> Consultants { get; set; }

    public virtual DbSet<ConsultantUserSchedule> ConsultantUserSchedules { get; set; }

    public virtual DbSet<ConsultationBooking> ConsultationBookings { get; set; }

    public virtual DbSet<MenstrualCycle> MenstrualCycles { get; set; }

    public virtual DbSet<OvulationReminder> OvulationReminders { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Test> Tests { get; set; }

    public virtual DbSet<TestBooking> TestBookings { get; set; }

    public virtual DbSet<TestResult> TestResults { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(entity =>
        {
            entity.HasKey(e => e.BlogId).HasName("PK__Blog__FA0AA72D7FDA1FBB");

            entity.ToTable("Blog");

            entity.Property(e => e.BlogId).HasColumnName("blogId");
            entity.Property(e => e.Author).HasColumnName("author");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.Image)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("image");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("title");

            entity.HasOne(d => d.AuthorNavigation).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.Author)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Blog__author__656C112C");
        });

        modelBuilder.Entity<Consultant>(entity =>
        {
            entity.HasKey(e => e.ConsultantId).HasName("PK__Consulta__8E3CA2FFD62B1AC0");

            entity.Property(e => e.ConsultantId).HasColumnName("consultantId");
            entity.Property(e => e.Bio)
                .HasColumnType("text")
                .HasColumnName("bio");
            entity.Property(e => e.Degree)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("degree");
            entity.Property(e => e.ExperienceYears).HasColumnName("experienceYears");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.Consultants)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultan__userI__5812160E");
        });

        modelBuilder.Entity<ConsultantUserSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("PK__Consulta__A532EDD4F3966EC7");

            entity.ToTable("ConsultantUserSchedule");

            entity.Property(e => e.ScheduleId).HasColumnName("scheduleId");
            entity.Property(e => e.ConsultantId).HasColumnName("consultantId");
            entity.Property(e => e.ConsultationBookingId).HasColumnName("consultationBookingId");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.DurationMinutes).HasColumnName("durationMinutes");
            entity.Property(e => e.Notes)
                .HasColumnType("text")
                .HasColumnName("notes");
            entity.Property(e => e.ScheduleDateTime)
                .HasColumnType("datetime")
                .HasColumnName("scheduleDateTime");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Consultant).WithMany(p => p.ConsultantUserSchedules)
                .HasForeignKey(d => d.ConsultantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultan__consu__05D8E0BE");

            entity.HasOne(d => d.ConsultationBooking).WithMany(p => p.ConsultantUserSchedules)
                .HasForeignKey(d => d.ConsultationBookingId)
                .HasConstraintName("FK__Consultan__consu__06CD04F7");

            entity.HasOne(d => d.User).WithMany(p => p.ConsultantUserSchedules)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultan__userI__04E4BC85");
        });

        modelBuilder.Entity<ConsultationBooking>(entity =>
        {
            entity.HasKey(e => e.ConsultationBookingId).HasName("PK__Consulta__3CF475EF6B987E53");

            entity.Property(e => e.ConsultationBookingId).HasColumnName("consultationBookingId");
            entity.Property(e => e.ConsultantId).HasColumnName("consultantId");
            entity.Property(e => e.Datetime)
                .HasColumnType("datetime")
                .HasColumnName("datetime");
            entity.Property(e => e.LinkConsultation)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("linkConsultation");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Consultant).WithMany(p => p.ConsultationBookings)
                .HasForeignKey(d => d.ConsultantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultat__consu__5CD6CB2B");

            entity.HasOne(d => d.User).WithMany(p => p.ConsultationBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultat__userI__5BE2A6F2");
        });

        modelBuilder.Entity<MenstrualCycle>(entity =>
        {
            entity.HasKey(e => e.CyclesId).HasName("PK__Menstrua__674DB3A5B98CCDEE");

            entity.Property(e => e.CyclesId).HasColumnName("cyclesId");
            entity.Property(e => e.AverageLength).HasColumnName("averageLength");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.MenstrualCycles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Menstrual__userI__52593CB8");
        });

        modelBuilder.Entity<OvulationReminder>(entity =>
        {
            entity.HasKey(e => e.ReminderId).HasName("PK__Ovulatio__09DAAAE3629E666E");

            entity.Property(e => e.ReminderId).HasColumnName("reminderId");
            entity.Property(e => e.ReminderDate)
                .HasColumnType("datetime")
                .HasColumnName("reminderDate");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.OvulationReminders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ovulation__userI__5535A963");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__A0D9EFC632536856");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasColumnName("paymentId");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.Method)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("method");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.TestBooking).HasColumnName("testBooking");
            entity.Property(e => e.TransactionTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("transactionTime");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.TestBookingNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.TestBooking)
                .HasConstraintName("FK__Payment__testBoo__75A278F5");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__userId__74AE54BC");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK__Question__6238D4B29169AB4C");

            entity.ToTable("Question");

            entity.Property(e => e.QuestionId).HasColumnName("questionId");
            entity.Property(e => e.AnswerText)
                .HasColumnType("text")
                .HasColumnName("answerText");
            entity.Property(e => e.ConsultantId).HasColumnName("consultantId");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.QuestionText)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("questionText");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Consultant).WithMany(p => p.Questions)
                .HasForeignKey(d => d.ConsultantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Question__consul__60A75C0F");

            entity.HasOne(d => d.User).WithMany(p => p.Questions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Question__userId__619B8048");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__CD98462A009F62C8");

            entity.ToTable("Role");

            entity.HasIndex(e => e.RoleName, "UQ__Role__B1947861F6EC6D1E").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("roleName");
        });

        modelBuilder.Entity<Test>(entity =>
        {
            entity.HasKey(e => e.TestId).HasName("PK__Test__A29BFB880CE45F61");

            entity.ToTable("Test");

            entity.Property(e => e.TestId).HasColumnName("testId");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price");
        });

        modelBuilder.Entity<TestBooking>(entity =>
        {
            entity.HasKey(e => e.TestBookingId).HasName("PK__TestBook__383DA4ED006E3D34");

            entity.ToTable("TestBooking");

            entity.Property(e => e.TestBookingId).HasColumnName("testBookingId");
            entity.Property(e => e.ScheduledDate)
                .HasColumnType("datetime")
                .HasColumnName("scheduledDate");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.TestId).HasColumnName("testId");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Test).WithMany(p => p.TestBookings)
                .HasForeignKey(d => d.TestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TestBooki__testI__6C190EBB");

            entity.HasOne(d => d.User).WithMany(p => p.TestBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TestBooki__userI__6B24EA82");
        });

        modelBuilder.Entity<TestResult>(entity =>
        {
            entity.HasKey(e => e.ResultId).HasName("PK__TestResu__C6EADC5BEDA8EA71");

            entity.ToTable("TestResult");

            entity.Property(e => e.ResultId).HasColumnName("resultId");
            entity.Property(e => e.DiagnosticResults)
                .HasColumnType("text")
                .HasColumnName("diagnosticResults");
            entity.Property(e => e.TestBlood)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("testBlood");
            entity.Property(e => e.TestId).HasColumnName("testId");
            entity.Property(e => e.TestSample)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("testSample");
            entity.Property(e => e.TestUrine)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("testUrine");
            entity.Property(e => e.TypeStis)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("typeSTIs");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Test).WithMany(p => p.TestResults)
                .HasForeignKey(d => d.TestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TestResul__testI__6FE99F9F");

            entity.HasOne(d => d.User).WithMany(p => p.TestResults)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TestResul__userI__6EF57B66");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__CB9A1CFFCCC3E71F");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__AB6E6164F3698CCD").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.Address)
                .HasColumnType("text")
                .HasColumnName("address");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fullName");
            entity.Property(e => e.Gender)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("gender");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("passwordHash");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phoneNumber");
            entity.Property(e => e.RoleId).HasColumnName("roleId");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User__roleId__4F7CD00D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}