// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TestBooking
{
    public int TestBookingId { get; set; }

    public int UserId { get; set; }

    public int TestId { get; set; }

    public DateTime ScheduledDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Test Test { get; set; }

    public virtual User User { get; set; }
}