// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

[Table("TestBooking")]
public partial class TestBooking
{
    [Key]
    [Column("testBookingId")]
    public Guid TestBookingId { get; set; }

    [Column("userId")]
    public Guid UserId { get; set; }

    [Column("testId")]
    public Guid TestId { get; set; }

    [Column("scheduledDate", TypeName = "datetime")]
    public DateTime ScheduledDate { get; set; }

    [Column("status")]
    [StringLength(20)]
    [Unicode(false)]

    public string Status { get; set; }

    [InverseProperty("TestBooking")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();
    [ForeignKey("TestId")]
    [InverseProperty("TestBookings")]
    public virtual Test Test { get; set; }
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
    [ForeignKey("UserId")]
    [InverseProperty("TestBookings")]
    public virtual User User { get; set; }
}