// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Models;

public partial class Transaction
{
    public long Id { get; set; }

    public DateTime CreateAt { get; set; }

    public string Url { get; set; }

    public Guid BookingId { get; set; }
    [ForeignKey(nameof(BookingId))]
    public virtual TestBooking Booking { get; set; }
}