<<<<<<< Updated upstream
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
=======
﻿using System;
>>>>>>> Stashed changes
using System.Collections.Generic;

namespace Repository.Models;

public partial class User
{
    public int UserId { get; set; }

<<<<<<< Updated upstream
    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }
=======
    public string FullName { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string PasswordHash { get; set; } = null!;

    public string? PhoneNumber { get; set; }

    public string? Gender { get; set; }

    public string? Address { get; set; }
>>>>>>> Stashed changes

    public int RoleId { get; set; }

    public DateTime? CreateAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

<<<<<<< Updated upstream
=======
    public virtual ICollection<ConsultantApplication> ConsultantApplicationReviewedByNavigations { get; set; } = new List<ConsultantApplication>();

    public virtual ICollection<ConsultantApplication> ConsultantApplicationUsers { get; set; } = new List<ConsultantApplication>();

>>>>>>> Stashed changes
    public virtual ICollection<ConsultantUserSchedule> ConsultantUserSchedules { get; set; } = new List<ConsultantUserSchedule>();

    public virtual ICollection<Consultant> Consultants { get; set; } = new List<Consultant>();

    public virtual ICollection<ConsultationBooking> ConsultationBookings { get; set; } = new List<ConsultationBooking>();

<<<<<<< Updated upstream
=======
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

>>>>>>> Stashed changes
    public virtual ICollection<MenstrualCycle> MenstrualCycles { get; set; } = new List<MenstrualCycle>();

    public virtual ICollection<OvulationReminder> OvulationReminders { get; set; } = new List<OvulationReminder>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

<<<<<<< Updated upstream
    public virtual Role Role { get; set; }
=======
    public virtual Role Role { get; set; } = null!;
>>>>>>> Stashed changes

    public virtual ICollection<TestBooking> TestBookings { get; set; } = new List<TestBooking>();

    public virtual ICollection<TestResult> TestResults { get; set; } = new List<TestResult>();
<<<<<<< Updated upstream
}
=======

    public virtual ICollection<UserMessage> UserMessageReceivers { get; set; } = new List<UserMessage>();

    public virtual ICollection<UserMessage> UserMessageSenders { get; set; } = new List<UserMessage>();
}
>>>>>>> Stashed changes
